# Generated by Django 3.1.6 on 2021-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicto', '0002_auto_20210528_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='category',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
