# Generated by Django 3.1.6 on 2021-06-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicto', '0004_auto_20210529_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='category',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='words',
            name='rword',
            field=models.TextField(),
        ),
    ]
