# Generated by Django 3.1.6 on 2021-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicto', '0009_auto_20210604_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='uses',
            field=models.TextField(),
        ),
    ]
